version: '3.9'

services:
  influxdb:
    image: influxdb:2.0.7
    hostname: influxdb
    volumes:
      - influxdb-storage:/mnt/shared/code/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=ggnanasekaran77@gmail.com
      - DOCKER_INFLUXDB_INIT_BUCKET=monitor_service
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=MH4q8EVp_lYz3F1nNLe0BeV-M4BM8tBVkBT-rI7N5733ybVrpM4iHc5LwOFtlfM6lqyUqE2RtGJNEAMMhM-gPA==
    healthcheck:
      test: ["CMD-SHELL", "influx ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  monitor_service:
    build: .
    hostname: monitor101
    ports:
      - "8000:8000"
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
volumes:
  influxdb-storage: 
