name: pytesting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: /home/runner/work/urlrag/urlrag/app
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test with pytest
        run: |
          cd app
          pytest --disable-pytest-warnings
